### ISSUE TITLE
Deprecation Notices with latest stdlib

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [willdurand/puppet-composer#49]
### Description

When using puppetlabs-stdlib-4.25.1 deprecation notices are triggered due to the use of both validate_bool and validate_string functions

### Steps to reproduce

composer and stdlib modules installed.

### Expected behavior

no notices, warnings, or errors

### Further details

puppet version 4.5.1
ubuntu 16.04

```
==> delengtest: Warning: This method is deprecated, please use the stdlib validate_legacy function,
==> delengtest:                     with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README.
==> delengtest:    (at /etc/puppetlabs/code/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> delengtest: Warning: This method is deprecated, please use the stdlib validate_legacy function,
==> delengtest:                     with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README.
==> delengtest:    (at /etc/puppetlabs/code/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
```
### Related issues

If you're aware of other issues or even issues in other libraries being used by this package then you should reference them here as they may help to solve the issue.

**Comment by jgrammen-agilitypr** [comment]
well I made an attempt at a pull request that switches to native data types. 
Not sure my changes are functional, let me know if I am going down the correct path.

**Comment by jgrammen-agilitypr** [comment]
I should note that the changes still need to be tested.

**Comment by Ma27** [comment]
currently building a VM, we'll see %)

**Comment by Ma27** [comment]
the tests remain green and it builds locally in a Vagrant box:

```
==> default: Running provisioner: puppet...
==> default: Running Puppet with default.pp...
==> default: Info: Loading facts
==> default: Info: Loading facts
==> default: Notice: Compiled catalog for localhost.localdomain in environment production in 0.21 seconds
==> default: Info: Applying configuration version '1527000353'
==> default: Notice: /Stage[main]/Composer/Package[wget]/ensure: created
==> default: Notice: /Stage[main]/Composer/Exec[composer-install]/returns: executed successfully
==> default: Notice: /Stage[main]/Composer/File[/usr/local/bin/composer]/mode: mode changed '0644' to '0755'
==> default: Notice: /Stage[main]/Composer/File[/usr/local/bin/composer]/seluser: seluser changed 'unconfined_u' to 'system_u'
==> default: Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
==> default: Notice: Applied catalog in 1.85 seconds
```

As this change is not OS-related, but a code change which affects the parser I'm quite confident that this should be fine for now.

Thanks a lot for your contribution :+1:
